public enum AbilityID
{
    none = 0,
    SuperDurability = 1,
    SuperGathering = 2,
    SuperStamina = 3,
    SuperAim = 4,
    DecreaseDizziness = 5,
    DecreasePoisoning = 6,
    DecreaseBleeding = 7,
    SuperFraction = 8,
    IncreasePoisoning = 9,
    IncreaseDezziness = 10,
    GatheringBonus = 11,
    SuperDamage = 12,
    SuperReload = 13,
    GroupDamage = 14,
    IncreaseHealth = 15,
    IncreaseFood = 16,
    IncreaseWater = 17,
    IncreaseStamina = 18,
    IncreaseSpeed = 19,
    RegenHealth = 20,
}