public enum CursorID
{
    None = 0,
    ItemPickupCursor = 1,
    TableUpgradeCurcor = 2,
    RestorableCursor = 3,
    DestroyableCursor = 4,
    LootObjectCursor = 5,
    TombCursor = 6,
    MinableCursor = 7,
    Furnace = 8,
    LoomCursor = 9,
    PickupTimeDelayCursor = 10,
    OpenDoorCursor = 11,
    CoastLootCursor = 12,
    ActivateObjectsCursor = 13,
    ProgressCursor = 14,
    DeadManLootCursor = 15,
    BombDestroyCursor = 16,
    ToggleInteractableCursor = 17,
    ItemsRelatedInteractableCursor = 18,
    QuestItemRelatedInteractableCursor = 19,
    HouseBuildingCursor = 20,
}
