
//AUTOGENERATED
namespace Game.Models
{
    public enum LocalizationLanguageID
    {
        None = 0,
        English = 1,
        Russian = 2,
        German = 3,
        Spanish = 4,
        Greek = 5,
        French = 6,
        Dutch = 7,
        Turkish = 8,
        Romanian = 9,
        Korean = 10,
        Portuguese = 11,

    }
}