namespace Game.Models
{
    public enum PlayerWeaponID
    {
        None = 0,
        tool_hook = 1,
        tool_hook_water = 2,
        tool_hammer = 3,
        tool_hatchet = 4,
        tool_hatchet_stone = 5,
        tool_hatchet_stone_strong = 6,
        tool_pickaxe = 7,
        tool_pickaxe_stone = 8,
        tool_pickaxe_stone_strong = 9,
        weapon_club_wooden = 10,
        weapon_crossbow_simple = 11,
        weapon_bow_hunting = 12,
        weapon_knife_metal = 13,
        weapon_knife_stone = 14,
        weapon_mace_bone = 15,
        weapon_muscet_3barrel = 16,
        weapon_muscet_epic_01 = 17,
        weapon_muscet_handmade = 18,
        weapon_pistol_handmade = 19,
        weapon_pistol_01 = 20,
        weapon_pistol_epic_01 = 21,
        weapon_spear_metal_melee = 22,
        weapon_muscet_lowquality = 23,
        weapon_spear_stone_melee = 24,
        weapon_spear_wooden_melee = 25,
        weapon_sword_rusted = 26,
        weapon_sword_saber = 27,
        tool_fishing_rod = 28,
        weapon_mystic_scythe = 29,
        tool_shovel = 30,
        weapon_knife_bone = 31,
        weapon_shield_wood = 32,
    }
}
