namespace Game.Models
{
    public enum WorldObjectID
    {
        None = 0,
        CampFire = 1,
        Furnance = 2,
        items_box_wooden_small = 3,
        items_box_wooden_large = 4,
        loot_container_barrel_red_M = 5, // не юзаем. Можно удалить...
        defense_barricade_wood = 6,
        defense_wall_wood_middle = 7,
        defense_wall_wood_high = 8,
        defense_wall_stone_middle = 9,
        defense_wall_stone_high = 10,
        loot_container_barrel = 11,
        loot_container_chest_basic = 12,
        loot_container_barrel_red = 13,
        loot_container_militarybox = 14,
        Tomb = 15,
        items_water_catcher = 16,
        items_loom = 17,
        loot_container_barrel_Day00 = 18,
        resource_pickup_stone_S = 19,
        resources_sugarcane = 20,
        pickup_banana_tree = 21,
        Bag_Pickup = 22,
        food_coconut = 23,
        enemy_zombie_base = 24,
        pickup_banana = 25,
        pickup_apple = 26,
        deleted = 27, //was deleted
        defense_door_wood = 28,
        defense_door_stone = 29,
        loot_container_chest_coast = 30,
        loot_container_epic = 31,
        brokable_door = 32,
        construction_wood_foundation_square = 33,
        construction_wood_foundation_strairs = 34,
        construction_wood_foundation_triangle = 35,
        construction_wood_roof_solid = 36,
        construction_wood_roof_square = 37,
        construction_wood_roof_triangle = 38,
        construction_wood_stairs_L = 39,
        construction_wood_stairs_straight = 40,
        construction_wood_wall_door = 41,
        construction_wood_wall_solid = 42,
        construction_wood_wall_window = 43,
        construction_wood_wall_triangle = 44,
        construction_wood_roof_corner = 45,
        construction_wood_wall_half = 46,
        drop_container = 47,
        drop_container_big = 48,
        trap_bear = 49,
        trap_thorns = 50,
        bag_pickup_floating = 51,
        construction_building_house = 52,
        construction_building_forge = 53,
        construction_building_tools = 54,
        construction_building_workshop = 55,
        construction_building_alchemy = 56,
        construction_building_fence = 57,
        construction_building_tower = 58,
        pickup_stone = 59,
        pickup_wood = 60,
        items_box_wooden_middle = 61,
    }
}
